apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: us6dy7vsn-go 
  janus-idp.io/tekton: us6dy7vsn-go
  backstage.io/kubernetes-id: us6dy7vsn-go
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: us6dy7vsn-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml