apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: us6dy7vsn-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: us6dy7vsn-go 
  name: us6dy7vsn-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: us6dy7vsn-go 
